# Generated by Django 4.2.7 on 2023-11-26 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('application_id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this Application', primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=10)),
                ('phone_num', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=300, null=True)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
