# Generated by Django 4.2.7 on 2023-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_property_preview_alter_property_sq_mt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='sq_mt',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
