# Generated by Django 4.2.7 on 2023-12-11 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_property_bathrooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(null=True, upload_to='property_photos'),
        ),
        migrations.AlterField(
            model_name='propertyimage',
            name='prop',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.property', verbose_name='Property'),
        ),
    ]
