# Generated by Django 4.2.7 on 2023-12-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_property_main_photo_alter_propertyimage_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='estate_id',
        ),
        migrations.AddField(
            model_name='property',
            name='identifier',
            field=models.CharField(default='sky', max_length=12, primary_key=True, serialize=False),
        ),
    ]
