# Generated by Django 4.2.7 on 2023-12-11 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_property_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='prop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.property', verbose_name='Property'),
        ),
    ]
