# Generated by Django 4.2.7 on 2023-12-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_propertyimage_image_alter_propertyimage_prop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='identifier',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
