# Generated by Django 4.2.7 on 2023-12-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_property_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='code_name',
            field=models.CharField(default='SKY3B3BT', max_length=12, unique=True),
        ),
    ]
