# Generated by Django 4.2.7 on 2023-12-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_property_code_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='code_name',
        ),
        migrations.AddField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=255, null=True, unique=True),
        ),
    ]
