# Generated by Django 4.2.7 on 2023-12-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_alter_property_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
