# Generated by Django 4.2.7 on 2023-12-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_property_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyimage',
            name='description',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
